plugin:
    name: 'shohabbos.friends::lang.plugin.name'
    description: 'shohabbos.friends::lang.plugin.description'
    author: Shohabbos
    icon: oc-icon-users
    homepage: 'https://itmaker.uz'
permissions:
    manage_friends:
        tab: 'shohabbos.friends::lang.plugin.name'
        label: 'Manage friends'